baseURL = "https://btnb.netlify.app/" # ←あなたのURLに変更してOK
languageCode = "ja"
title = "My Hugo Site"
theme = "ananke"
enableRobotsTXT = true
paginate = 10

[params]
  author = "カイヌシ"
  favicon = "images/favicon.ico"
  description = "これはHugo + Anankeで作られたサイトです。"

[markup]
  defaultMarkdownHandler = "goldmark"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/posts/:slug/"
