baseURL = "https://btnb.netlify.app/" # ←あなたのURLに変更してOK
languageCode = "ja"
title = "btnb/portfolio"
theme = "ananke"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "彩まそほ"
  favicon = "images/favicon.ico"
  description = "これはHugo + Anankeで作られたサイトです。"

[markup]
  defaultMarkdownHandler = "goldmark"

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/posts/:slug/"
