baseURL = "https://btnb.netlify.app/" # ←あなたのURLに変更してOK
languageCode = "ja"
title = "btnb/portfolio"
theme = "guardian"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "彩まそほ"
  favicon = "images/btnb.ico"
  description = "portfolioサイトです。"

[markup]
  defaultMarkdownHandler = "goldmark"

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/posts/:slug/"
  
[taxonomies]
  tag = "tags"
  category = "categories"
