[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  GIT_SUBMODULE_STRATEGY = "recursive"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
