name = "guardian"
license = "MIT"
description = "Custom guardian theme"


homepage = "https://github.com/btnb/guardian"
demosite = "https://art.btnb.jp"

tags = ["portfolio", "art", "gallery"]
features = ["responsive", "custom", "minimal"]

[author]
  name = "btnb"
  homepage = "https://art.btnb.jp"
